name: Clear
on:
  workflow_dispatch:
  schedule:
    - cron: '3/10 * * * * '

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Delete artifacts
        run: |
          json=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LucasDREZET/PrivateCypress/actions/artifacts -u ${{ secrets.USER }}:${{ secrets.PAT }}
          total=`echo $json | jq -r '.total_count'`
          if [[ $total != 0 ]]; then
            i=0
            while [ $i -lt $total ]
            do
              curl -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LucasDREZET/PrivateCypress/actions/artifacts/`echo $json | jq -r ".artifacts[$i].id"` -u ${{ secrets.USER }}:${{ secrets.PAT }}
              ((i++))
            done
          fi