name: Cypress
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Put code
        id: putCode
        run: echo "${{ secrets.CODE }}" >> ./cypress/integration/test.js

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          record: false
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check files
        id: file
        run: ls ./cypress/screenshots/test.js/dispo.png
        continue-on-error: true

      - name: Notification failure
        id: failureNotif
        if: ${{ steps.cypress.outcome == 'success' }}
        run: curl -F "file1=@cypress/screenshots/test.js/dispo.png" ${{ secrets.WEBHOOK_FAIL }}
        continue-on-error: true
        
      - name: Notification crash
        id: crashNotif
        if: ${{ steps.cypress.outcome == 'failure' && steps.file.outcome == 'failure' }}
        run: curl -F 'payload_json={"content":"Error! Check here:\nhttps://github.com/LucasDREZET/PrivateCypress/actions/runs/${{ github.run_id }}"}' ${{ secrets.WEBHOOK_FAIL }}

      - name: Notification success
        id: successNotif
        if: ${{ steps.cypress.outcome == 'failure' && steps.file.outcome == 'success' }}
        run: curl -F 'payload_json={"content":"${{ secrets.MESSAGE }}"}' -F "file1=@cypress/screenshots/test.js/dispo.png" ${{ secrets.WEBHOOK_SUCCESS }}
        continue-on-error: true

      - name: Launch new workflow
        if: ${{ always() }}
        run: curl -X POST -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/LucasDREZET/PrivateCypress/actions/workflows/cypress.yml/dispatches -u ${{ secrets.USER }}:${{ secrets.PAT }} -d '{"ref":"main"}'
