name: Cypress
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        
      - name: Notification hello
        run: curl -H "Content-Type:application/json" -d '{"content":"Hello! https://github.com/LucasDREZET/PrivateCypress/actions/runs/${{ github.run_id }}"}' ${{ secrets.WEBHOOK_HELLO }}

      - name: Put code
        id: putCode
        run: echo "${{ secrets.CODE }}" >> ./cypress/integration/test.js

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          record: false
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Notification failure
        if: ${{ failure() }}
        run: curl -H "Content-Type:application/json" -d '{"content":"https://github.com/LucasDREZET/PrivateCypress/actions/runs/${{ github.run_id }}"}' ${{ secrets.WEBHOOK_FAIL }}

      - name: Launch new workflow
        if: ${{ always() }}
        run: |
          sleep 1
          curl -X POST -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/LucasDREZET/PrivateCypress/actions/workflows/cypress.yml/dispatches -u ${{ secrets.USER }}:${{ secrets.PAT }} -d '{"ref":"main"}'
